"use client";
import { useCallback, useEffect, useState } from "react";
import { Activity, Bell, CheckCircle2, ChevronRight, Cloud, Gauge, Layers, Loader2, Pause, Play, Plus, RefreshCw, Search, ShieldCheck, Terminal, TriangleAlert } from "lucide-react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import type { Snapshot, Incident, Health } from "../core/types";
type Monitor = Snapshot["services"][number];
async function api(path: string, payload?: unknown, method = "POST") {
  const response = await fetch(`/api/${path}`, payload === undefined ? { cache: "no-store" } : { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) });
  const d = await response.json() as Record<string, unknown>; if (!response.ok) throw new Error(String(d.error ?? "Request failed.")); return d;
}
const time = (s: string) => new Date(s).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
const dt = (s: string) => new Date(s).toLocaleString([], { month: "short", day: "numeric", hour: "2-digit", minute: "2-digit" });
function Badge({ state }: { state: string }) { return <span className={`status status-${state}`}><span />{state === "healthy" ? "Operational" : state === "unknown" ? "Awaiting check" : state.charAt(0).toUpperCase() + state.slice(1)}</span>; }
function Choice({ value, onChange, choices, label }: { value: string; onChange: (v: string) => void; choices: [string, string][]; label: string }) { return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="choice"><SelectValue /></SelectTrigger><SelectContent>{choices.map(([v,t]) => <SelectItem key={v} value={v}>{t}</SelectItem>)}</SelectContent></Select>; }
function History({ service }: { service: Monitor }) { return <div className="history" aria-label={`${service.name}: recent checks`}>{service.checks.slice(-48).map(c => <span key={c.id} className={`history-bar ${c.status}`} title={`${dt(c.checkedAt)} · ${c.status} · ${c.latencyMs ?? "timeout"}${c.latencyMs !== null ? " ms" : ""}${c.simulated ? " · simulated" : ""}`} />)}{!service.checks.length && <span className="metadata">No measurements yet</span>}</div>; }
export default function Dashboard() {
  const [data,setData] = useState<Snapshot|null>(null), [tab,setTab] = useState("overview"), [error,setError] = useState(""), [notice,setNotice] = useState(""), [busy,setBusy] = useState(false);
  const [modal,setModal] = useState<"monitor"|"incident"|null>(null), [inspect,setInspect] = useState<Monitor|null>(null), [detail,setDetail] = useState<Incident|null>(null);
  const [search,setSearch] = useState(""), [filter,setFilter] = useState("active"), [demoState,setDemoState] = useState<Health>("healthy"), [note,setNote] = useState("");
  const [form,setForm] = useState({ name:"", target:"", region:"ap-south-1", group:"API", mode:"demo", title:"", description:"", serviceId:"", severity:"warning" });
  const load = useCallback(async () => { const d = await api("dashboard") as unknown as Snapshot; setData(d); return d; }, []);
  const act = useCallback(async (work:()=>Promise<unknown>, message:string) => { setBusy(true); setError(""); try { await work(); const d=await load(); setNotice(message); return d; } catch(e) { setError(e instanceof Error ? e.message : "Please retry."); return null; } finally { setBusy(false); } }, [load]);
  useEffect(() => { let active=true; load().catch(e=>{if(active)setError(e.message)}); const timer=setInterval(()=>{void api("checks",{}).then(load).catch(e=>{if(active)setError(e.message)})},60000); return ()=>{active=false;clearInterval(timer)}; },[load]);
  useEffect(()=>{if(!notice)return;const timer=setTimeout(()=>setNotice(""),6000);return()=>clearTimeout(timer)},[notice]);
  useEffect(()=>{
    const ctx=(document as unknown as {modelContext?:{registerTool:(tool:object,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!ctx?.registerTool)return;const controller=new AbortController();
    const valid=(input:unknown)=>{if(input===null||typeof input!=="object"||Object.keys(input).length)throw new Error("Expected an empty object.")};
    for(const tool of [
      {name:"read_cloudpulse_dashboard",description:"Read monitor health and incidents, and refresh the dashboard.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{valid(input);const d=await load();return {services:d.services.map(s=>({id:s.id,name:s.name,status:s.status})),incidents:d.incidents.map(i=>({id:i.id,title:i.title,status:i.status}))}}},
      {name:"run_cloudpulse_checks",description:"Run probes, save measurements, create or resolve automatic incidents, and refresh the dashboard.",inputSchema:{type:"object",properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{valid(input);const d=await act(()=>api("checks",{}),"Health checks completed.");if(!d)throw new Error("Checks failed.");return d.stats}}
    ]){try{Promise.resolve(ctx.registerTool(tool,{signal:controller.signal})).catch(()=>{})}catch{}}return()=>controller.abort();
  },[load,act]);
  const open=(type:"monitor"|"incident")=>{setError("");setForm(f=>({...f,name:"",target:"",title:"",description:"",serviceId:data?.services[0]?.id??""}));setModal(type)};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();const ok=await act(()=>modal==="monitor"?api("services",{name:form.name,target:form.target,mode:form.mode,region:form.region,group:form.group}):api("incidents",{title:form.title,description:form.description,serviceId:form.serviceId,severity:form.severity}),modal==="monitor"?"Monitor added.":"Incident reported.");if(ok)setModal(null)};
  const updateIncident=async(i:Incident,status:string)=>{if(await act(()=>api(`incidents/${i.id}`,{status,note},"PATCH"),`Incident ${status}.`)){setDetail(null);setNote("")}};
  const inspectService=(s:Monitor)=>{setInspect(s);setDemoState(s.demoState);setError("")};
  const active=data?.incidents.filter(i=>i.status!=="resolved")??[], services=data?.services.filter(s=>`${s.name} ${s.group} ${s.region}`.toLowerCase().includes(search.toLowerCase()))??[];
  const incidents=data?.incidents.filter(i=>filter==="all"||(filter==="active"?i.status!=="resolved":i.status==="resolved"))??[];
  const incidentCard=(i:Incident)=><button key={i.id} className="incident-card" onClick={()=>{setDetail(i);setNote("");setError("")}}><span className={`incident-symbol ${i.severity}`}><TriangleAlert size={19}/></span><span className="incident-info"><span className="incident-top"><span className={`severity ${i.severity}`}>{i.severity==="critical"?"P1":"P2"}</span><span className="metadata">{dt(i.createdAt)}</span></span><strong>{i.title}</strong><span className="metadata">{data?.services.find(s=>s.id===i.serviceId)?.name} · {i.status} · {i.source==="monitor"?"Automatic":"Reported"}</span></span><ChevronRight size={17}/></button>;
  const table=<Table className="monitor-table"><TableHeader><TableRow><TableHead>Service</TableHead><TableHead>Status</TableHead><TableHead>Recent checks</TableHead><TableHead>Response</TableHead><TableHead>Availability</TableHead><TableHead><span className="sr-only">Inspect</span></TableHead></TableRow></TableHeader><TableBody>{services.map(s=><TableRow key={s.id}><TableCell><button className="service-name" onClick={()=>inspectService(s)}><span className={`service-icon ${s.group.toLowerCase()}`}><Layers size={18}/></span><span><strong>{s.name}</strong><span className="metadata">{s.region} · {s.mode==="demo"?"Simulated":"Live"}</span></span></button></TableCell><TableCell><Badge state={s.paused?"paused":s.status}/></TableCell><TableCell><History service={s}/></TableCell><TableCell className="mono">{s.latency===null?"—":`${s.latency} ms`}</TableCell><TableCell className="mono">{s.uptime===null?"—":`${s.uptime.toFixed(1)}%`}</TableCell><TableCell><Button variant="ghost" className="icon-button" aria-label={`Inspect ${s.name}`} onClick={()=>inspectService(s)}><ChevronRight size={18}/></Button></TableCell></TableRow>)}</TableBody></Table>;
  return <div className="workspace"><header className="app-header"><div className="brand"><span className="brand-icon"><Activity size={24}/></span><strong>CloudPulse <span className="brand-divider">/</span></strong><span className="workspace-name">Operations</span></div><div className="header-meta"><span className="private-label"><ShieldCheck size={15}/> Private workspace</span><span className="avatar">SG</span></div></header><main>
    <div className="page-heading"><div><p className="eyebrow">RELIABILITY WORKSPACE</p><h1>Service overview</h1><p className="subtitle">A clear view of what’s running, and what needs attention.</p></div><div className="heading-actions"><Button className="btn-secondary" onClick={()=>open("incident")} disabled={!data||busy}><Plus size={17}/> Report incident</Button><Button className="btn-primary" disabled={busy||!data} onClick={()=>act(()=>api("checks",{}),"Health checks completed.")}>{busy?<Loader2 className="spin" size={17}/>:<RefreshCw size={17}/>} Run checks</Button></div></div>
    <div className="practice-banner"><span className="practice-tag"><Terminal size={14}/> PRACTICE LAB</span><p>Starter services use simulated checks. CloudPulse API measures database readiness. Add your own HTTPS monitors for live checks.</p></div>
    {error&&<div className="error-banner" role="alert"><TriangleAlert size={17}/><span>{error}</span><Button variant="ghost" onClick={()=>setError("")}>Dismiss</Button></div>}{notice&&<div className="notice" role="status"><CheckCircle2 size={17}/>{notice}</div>}
    {!data?<div className="loading-panel"><Loader2 className="spin"/><p>{error?"Could not load the workspace.":"Loading your workspace…"}</p>{error&&<Button className="btn-secondary" onClick={()=>act(load,"Workspace refreshed.")}>Retry</Button>}</div>:<>
    <div className="metrics"><article className="metric"><div className="metric-label">Healthy services<Layers size={17}/></div><div className="metric-value">{data.stats.healthy}<span>/ {data.services.filter(s=>!s.paused).length}</span></div><p><span className="metric-positive">{data.stats.degraded+data.stats.down} need attention</span> · {data.services.filter(s=>s.status==="unknown"&&!s.paused).length} awaiting check</p></article><article className="metric"><div className="metric-label">Check availability<Activity size={17}/></div><div className="metric-value">{data.stats.uptime===null?"—":data.stats.uptime.toFixed(2)}<span>%</span></div><p>Successful responses · collected checks</p></article><article className="metric"><div className="metric-label">Average response<Gauge size={17}/></div><div className="metric-value">{data.stats.latency??"—"}<span>ms</span></div><p>Latest response per service</p></article><article className="metric"><div className="metric-label">Active incidents<Bell size={17}/></div><div className="metric-value amber">{data.stats.activeIncidents}<span>open</span></div><p>{active.filter(i=>i.severity==="critical").length} critical · {active.filter(i=>i.severity==="warning").length} warning</p></article></div>
    <Tabs value={tab} onValueChange={setTab} className="main-tabs"><div className="tab-bar"><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="monitors">Monitors <span className="count">{data.services.length}</span></TabsTrigger><TabsTrigger value="incidents">Incidents <span className="count">{active.length}</span></TabsTrigger></TabsList><span className="metadata refresh-label">Updated {time(data.generatedAt)} · checks every 60s while open</span></div>
      <TabsContent value="overview"><div className="overview-grid"><section className="panel chart-panel"><div className="panel-heading"><div><h2>Response time</h2><p className="metadata">Average across monitors · includes practice samples</p></div><span className="chart-key"><span/> Response (ms)</span></div><div className="chart"><ResponsiveContainer width="100%" height={230}><AreaChart data={data.series} margin={{top:16,right:15,bottom:0,left:0}}><defs><linearGradient id="latency-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8d79ff" stopOpacity={.25}/><stop offset="100%" stopColor="#8d79ff" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#29303a" strokeDasharray="3 4" vertical={false}/><XAxis dataKey="at" tickFormatter={time} minTickGap={45} tick={{fill:"#8f99ab",fontSize:12}} axisLine={false} tickLine={false}/><YAxis width={43} tick={{fill:"#8f99ab",fontSize:12}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:"#1b202b",border:"1px solid #3c4352",borderRadius:8,color:"#fafbff"}} labelFormatter={v=>dt(String(v))} formatter={v=>[`${v} ms`,"Average response"]}/><Area type="monotone" dataKey="latency" stroke="#a590ff" strokeWidth={2.5} fill="url(#latency-fill)" isAnimationActive={false}/></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span>{data.stats.checks} retained measurements</span><span>Slow &gt; 1,000 ms · down on failure</span></div></section><section className="panel incident-panel"><div className="panel-heading"><h2>Needs attention <span className="count">{active.length}</span></h2><Button variant="ghost" className="text-button" onClick={()=>setTab("incidents")}>View all</Button></div>{active.length?active.slice(0,3).map(incidentCard):<div className="empty"><CheckCircle2/><strong>No active incidents</strong><p>Your services are ready for the next check.</p></div>}<div className="incident-tip"><ShieldCheck size={17}/><span>Acknowledge, investigate, then resolve.</span></div></section></div><section className="panel services-panel"><div className="panel-heading"><div><h2>Monitored services</h2><p className="metadata">Availability uses up to 96 retained checks per service.</p></div><Button className="btn-secondary btn-small" onClick={()=>open("monitor")}><Plus size={16}/> Add monitor</Button></div>{table}</section></TabsContent>
      <TabsContent value="monitors"><section className="panel services-panel"><div className="panel-heading"><div><h2>Monitors</h2><p className="metadata">Inspect to pause checks or simulate a failure.</p></div><Button className="btn-primary" onClick={()=>open("monitor")}><Plus size={16}/> Add monitor</Button></div><div className="filter-row"><label className="search"><Search size={17}/><input aria-label="Search monitors" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Find a service, group, or region"/></label><span className="metadata">{services.length} services</span></div>{services.length?table:<div className="empty"><Search/><strong>No matching services</strong><p>Try a different search.</p></div>}</section></TabsContent>
      <TabsContent value="incidents"><section className="panel full-incidents"><div className="panel-heading"><div><h2>Incident log</h2><p className="metadata">Automatic incidents resolve when a service recovers.</p></div><Button className="btn-primary" onClick={()=>open("incident")}><Plus size={16}/> Report incident</Button></div><div className="filter-row"><Choice value={filter} onChange={setFilter} label="Filter incidents" choices={[["active","Active incidents"],["resolved","Resolved incidents"],["all","All incidents"]]}/><span className="metadata">{incidents.length} incidents</span></div>{incidents.length?incidents.map(incidentCard):<div className="empty"><CheckCircle2/><strong>No {filter==="all"?"":filter} incidents</strong><p>New incidents will appear here.</p></div>}</section></TabsContent>
    </Tabs><footer className="app-footer"><span><Cloud size={15}/> CloudPulse · Cloud operations project</span><span>History persists across sessions · simulated data is labeled</span></footer></>}
  </main>
  <Dialog open={modal!==null} onOpenChange={v=>{if(!v)setModal(null)}}><DialogContent className="cp-dialog"><DialogHeader><DialogTitle>{modal==="monitor"?"Add a monitor":"Report an incident"}</DialogTitle><DialogDescription>{modal==="monitor"?"Use a practice service or a configured public HTTPS endpoint.":"Capture the impact and affected service."}</DialogDescription></DialogHeader><form onSubmit={submit} className="cp-form">{modal==="monitor"?<><label>Name<input required maxLength={80} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Payments API"/></label><label>Monitor type<Choice value={form.mode} onChange={mode=>setForm({...form,mode})} label="Monitor type" choices={[["demo","Practice service"],["http","Live HTTPS endpoint"]]}/></label>{form.mode==="http"&&<label>Health URL<input required type="url" maxLength={1024} value={form.target} onChange={e=>setForm({...form,target:e.target.value})} placeholder="https://your-service.com/health"/><span className="metadata">Enabled hosts: {data?.allowedHosts.join(", ")||"None yet. Enable your domain using the deployment guide."}</span></label>}<div className="form-grid"><label>Region<input required value={form.region} maxLength={40} onChange={e=>setForm({...form,region:e.target.value})}/></label><label>Group<Choice value={form.group} onChange={group=>setForm({...form,group})} label="Service group" choices={[["API","API"],["Web","Web"],["Worker","Worker"],["Storage","Storage"]]}/></label></div></>:<><label>Title<input required maxLength={160} value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Describe the issue"/></label><label>Affected service<Choice value={form.serviceId} onChange={serviceId=>setForm({...form,serviceId})} label="Affected service" choices={data?.services.map(s=>[s.id,s.name])??[]}/></label><label>Severity<Choice value={form.severity} onChange={severity=>setForm({...form,severity})} label="Severity" choices={[["warning","P2 · Warning"],["critical","P1 · Critical"]]}/></label><label>Description<textarea required rows={3} maxLength={2000} value={form.description} onChange={e=>setForm({...form,description:e.target.value})} placeholder="Impact, symptoms, and initial investigation"/></label></>}{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-actions"><Button type="button" className="btn-secondary" onClick={()=>setModal(null)}>Cancel</Button><Button type="submit" className="btn-primary" disabled={busy}>{busy?"Saving…":modal==="monitor"?"Add monitor":"Report incident"}</Button></div></form></DialogContent></Dialog>
  <Dialog open={inspect!==null} onOpenChange={v=>{if(!v)setInspect(null)}}><DialogContent className="cp-dialog"><DialogHeader><DialogTitle>{inspect?.name}</DialogTitle><DialogDescription>{inspect?.mode==="demo"?"Practice monitor · simulated measurements":"Live monitor · measured in this runtime"}</DialogDescription></DialogHeader>{inspect&&<div className="cp-form"><div className="detail-grid"><span>Endpoint</span><code>{inspect.target}</code><span>Latest check</span><span>{inspect.lastCheckedAt?dt(inspect.lastCheckedAt):"Not checked yet"}</span><span>Result</span><span>{inspect.checks.at(-1)?.message??"Run checks to collect a measurement."}</span></div><History service={inspect}/>{inspect.mode==="demo"&&<label>Simulate service state<Choice value={demoState} onChange={v=>setDemoState(v as Health)} label="Simulated state" choices={[["healthy","Operational"],["degraded","Slow response"],["down","Unavailable"]]}/><span className="metadata">Run a check to record this state and trigger incident handling.</span></label>}{error&&<p className="form-error">{error}</p>}<div className="form-actions"><Button className="btn-secondary" disabled={busy} onClick={async()=>{if(await act(()=>api(`services/${inspect.id}`,{paused:!inspect.paused},"PATCH"),inspect.paused?"Monitor resumed.":"Monitor paused."))setInspect(null)}}>{inspect.paused?<Play size={16}/>:<Pause size={16}/>} {inspect.paused?"Resume":"Pause"}</Button><Button className="btn-primary" disabled={busy||inspect.paused} onClick={async()=>{if(await act(async()=>{if(inspect.mode==="demo")await api(`services/${inspect.id}`,{demoState},"PATCH");return api("checks",{})},"Checks completed."))setInspect(null)}}>{busy?"Checking…":"Apply & run checks"}</Button></div></div>}</DialogContent></Dialog>
  <Dialog open={detail!==null} onOpenChange={v=>{if(!v)setDetail(null)}}><DialogContent className="cp-dialog"><DialogHeader><DialogTitle>{detail?.title}</DialogTitle><DialogDescription>{detail?.source==="monitor"?"Automatic incident":"Reported incident"} · {detail&&dt(detail.createdAt)}</DialogDescription></DialogHeader>{detail&&<div className="cp-form"><Badge state={detail.status}/><p className="incident-description">{detail.description}</p><ol className="timeline">{detail.notes.map((n,i)=><li key={i}><span className="metadata">{dt(n.at)}</span><p>{n.text}</p></li>)}</ol>{detail.status!=="resolved"&&<><label>Investigation or resolution note<textarea rows={2} maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="What did you find or change?"/></label>{error&&<p className="form-error">{error}</p>}<div className="form-actions">{detail.status==="open"&&<Button className="btn-secondary" disabled={busy} onClick={()=>updateIncident(detail,"acknowledged")}>Acknowledge</Button>}<Button className="btn-primary" disabled={busy} onClick={()=>updateIncident(detail,"resolved")}><CheckCircle2 size={17}/> Resolve incident</Button></div></>}</div>}</DialogContent></Dialog>
  </div>;
}
